### ISSUE TITLE
Client is set to internal

### ISSUE THREAD

**Issue by gbachs** [DimensionDataCBUSydney/Meraki.Dashboard#3]
The documentation states to use the Client property on MerakiDashboardClient in instances where the library does not support certain API calls but the property is set to internal.

**Comment by anthonylangsworth** [comment]
Thanks for the feedback, @gbachs. I am happy to make it public.  Feel free to submit a pull request. Otherwise, I will try to get to it over the next few days.

**Comment by anthonylangsworth** [comment]
I managed to find time to fix this and pushed a fix. The new NuGet package should be available in a few hours. Please let me know if you have further questions or issues.

**Comment by anthonylangsworth** [comment]
Closing.
